apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shop-gw
spec:
  commonName: shop-gw.viktoriouslab.nl
  dnsNames:
    - shop-gw.viktoriouslab.nl
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  secretName: shop-gw
