apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-gw
spec:
  commonName: bookinfo-gw.viktoriouslab.nl
  dnsNames:
    - bookinfo-gw.viktoriouslab.nl
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  secretName: bookinfo-gw
