apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "01-default-pool"
spec:
  cidrs:
  - cidr: "172.16.101.0/24"
  serviceSelector:
    matchExpressions:
      - {key: "io.kubernetes.service.namespace", operator: NotIn, values: ["shop"]}
