apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
spec:
  cidrs:
  - cidr: "172.16.101.0/24"
  serviceSelector:
     matchExpressions:
       "io.kubernetes.service.namespace": "shop"