apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "02-pool-with-selector"
spec:
  cidrs:
  - cidr: "172.16.102.0/24"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.namespace": "shop"