apiVersion: v1
kind: Secret
metadata:
  name: git-https-secret
  namespace: tap-install
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
# Setup a fine grained personal access token (if using GitHub) to provide access to your TAP deliveries Git Repository
# https://github.com/settings/tokens?type=beta
stringData:
  username: <github-username>
  password: <github-password>
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-https-secret
  namespace: tap-install
spec:
  toNamespaces:
    - '*'