apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: lsp-pull-credentials
  namespace: tap-install
data:
  .dockerconfigjson: <dockerconfigjson>
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: lsp-push-credentials
  namespace: tap-install
data:
  .dockerconfigjson: <dockerconfigjson>
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: lsp-push-credentials
  namespace: tap-install
spec:
  toNamespace: tap-local-source-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: lsp-pull-credentials
  namespace: tap-install
spec:
  toNamespace: *