#@ load("@ytt:data", "data")
---
#! Secret for github.com repos
apiVersion: v1
kind: Secret
metadata:
  namespace: #@ data.values.git.namespace
  name: #@ data.values.git.name
  annotations:
    tekton.dev/git-0: #@ data.values.git.host 
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.git.username
  password: #@ data.values.git.password
---
#! Export the secret
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.git.name
  namespace: #@ data.values.git.namespace
spec:
  toNamespaces:
    - '*'

---
#! Secret for local_source_proxy repository access
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: #@ data.values.local_source_proxy.namepull
  namespace: #@ data.values.local_source_proxy.namespace
data:
  .dockerconfigjson: #@ data.values.local_source_proxy.configjson
---
#! Export the secret
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.local_source_proxy.namepull
  namespace: #@ data.values.local_source_proxy.namespace
spec:
  toNamespaces:
    - '*'

---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: #@ data.values.local_source_proxy.namepush
  namespace: #@ data.values.local_source_proxy.namespace
data:
  .dockerconfigjson: #@ data.values.local_source_proxy.configjson
---
#! Export the secret
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.local_source_proxy.namepush
  namespace: #@ data.values.local_source_proxy.namespace
spec:
  toNamespaces:
    - tap-local-source-system