apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tkg01
  namespace: ns01
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.26.5---vmware.2-fips.1-tkg
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 4
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: vc01cl01-t0compute
      - name: defaultStorageClass
        value: vc01cl01-t0compute
      #Add 70GB local storage to each K8S worker node
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: 70G
          mountPath: /var/lib/containerd
          name: extrastorage01
          storageClass: vc01cl01-t0compute
