apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tkg02
  namespace: ns01
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.20.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/16
  topology:
    class: tanzukubernetescluster
    controlPlane:
      replicas: 1
    variables:
    - name: vmClass
      value: best-effort-2xlarge
    - name: nodePoolVolumes
      value:
      - capacity:
          storage: 125G
        mountPath: /var/lib/kubelet
        name: kubelet
        storageClass: vc01cl01-t0compute
      - capacity:
          storage: 70G
        mountPath: /var/lib/containerd
        name: containerd
        storageClass: vc01cl01-t0compute
    - name: storageClass
      value: vc01cl01-t0compute
    - name: controlPlaneVolumes
      value:
      - capacity:
          storage: 125G
        mountPath: /var/lib/kubelet
        name: kubelet
        storageClass: vc01cl01-t0compute
      - capacity:
          storage: 70G
        mountPath: /var/lib/containerd
        name: containerd
        storageClass: vc01cl01-t0compute
    version: v1.26.5+vmware.2-fips.1
    workers:
      machineDeployments:
      - class: node-pool
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu,os-version=20.04,os-arch=amd64
        name: md-0
        replicas: 3
        variables:
          overrides:
          - name: vmClass
            value: best-effort-2xlarge
