apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-svc
  name: nginx03
  namespace: pv
spec:
#  volumes:
#    - name: task-pv-storage
#      persistentVolumeClaim:
#        claimName: pvc01
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 80
#    volumeMounts:
#    - mountPath: "/usr/share/nginx/html"
#      name: task-pv-storage
  # regcred contains Dockerhub credentials, remove if not necessary
  imagePullSecrets:
  - name: regcred
