apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc02
  name: nginx-svc02
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx02
  type: LoadBalancer
status:
  loadBalancer: {}
