apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc04
  name: nginx-svc04
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx04
  type: LoadBalancer
status:
  loadBalancer: {}
