apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: web.viktoriouslab.nl
spec:
  commonName: web.viktoriouslab.nl
  dnsNames:
    - web.viktoriouslab.nl
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  secretName: harbor.viktoriouslab.nl
