AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5ekNDQXJPZ0F3SUJBZ0lVRHBxOFFPVmtmTko4bU5HeHlmOVcxQTVhZVNVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZTXhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVNNQkFHQTFVRUJ3d0pVR0ZzYnlCQgpiSFJ2TVE4d0RRWURWUVFLREFaV1RYZGhjbVV4RERBS0JnTlZCQXNNQTBneVR6RU9NQXdHQTFVRUF3d0ZZWFpwCk1ERXhKREFpQmdrcWhraUc5dzBCQ1FFV0ZYQmxlbk4xY0hCdmNuUkFkbTEzWVhKbExtTnZiVEFlRncweU16QTUKTVRFeE5ETTRORFZhRncweU5EQTVNVEF4TkRNNE5EVmFNSUdETVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRQpDQXdDUTBFeEVqQVFCZ05WQkFjTUNWQmhiRzhnUVd4MGJ6RVBNQTBHQTFVRUNnd0dWazEzWVhKbE1Rd3dDZ1lEClZRUUxEQU5JTWs4eERqQU1CZ05WQkFNTUJXRjJhVEF4TVNRd0lnWUpLb1pJaHZjTkFRa0JGaFZ3WlhwemRYQncKYjNKMFFIWnRkMkZ5WlM1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDOApuaDNOdEZ1MlpMZjlQczQ1TkdNc056MituaGJZcEJJaTRMZVh4cmwxMS8xMkxOYzJSUU5nV2RINWdRV1owUFEyCnlpVUVjZHRFcHhuOG8xKzlwViswUEVIYzlzaGRqTG9ISmhNZnZpeTNFRzVENjkwYW4xYjRJZFJESU5XYi9FWUsKVTJ4dE0rTngwL2s5UHdtMjV4Q3ZZYXFBMVNjVXZrWmxhend1TTkvMWx3OE13SERBdlNDdGFpTUNkdzV5TWtZRwpIMlZ2MW5mUFNMaFlra1ZlSWIyang4OFo5MmV5N1lEa1dXVGdMUVR3R0VFdUJGamVMQWs4QldoSEJrL1JGR200CnoybnhsS1QzRS94RkhYR09tMjZ3VnpKWGpQeEpJalp6RG9WVjNIcWdSNDJYNmtwSjRxYkU1bkxpZlpIVHZkb3UKMWhRZU4rdDU5RVRRSVFDYUJKek5BZ01CQUFHak5UQXpNREVHQTFVZEVRUXFNQ2lDSUdGMmFUQXhMbWd5YnkwMApMVEU0TlRJM0xtZ3lieTUyYlhkaGNtVXVZMjl0aHdRSzFyYmlNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFXCnJVYjc1cTZQMHhTMjl2V0szYU5SWW9WK2VjM0p5SFBxWXN0c1lPQnJ3Z0w1U3pUVzBVY3Bick5OWEhaaTQvdkwKSG1tVmZqd0l6TXZiM1E0V0s2a29aSWpLcXRYOERhMGcwNEdmVTNjZ1djQXR2bGhibmFoZGpaVGVWUzFGRytYQwovMmhqcXg3V3V1akFzSjU2emc3R0ZTU2loWkVZV1BXMnBCQ2ZKd3RIZ2daV0UxZVBtemhBcW4vS3k5MlBrTGowCkcyUXNzL0kvOUFzcEVzVEk2NGdraEkyQjBTSFFPVUlPQXhkYmhFMHJISlB2bGk2emJSa3pQY0M3Z09uNjM3QUcKVzFsdmxqQWpNY3cvclJwL0hxdFBGa1FzcDBBMTFtUlZHSEpsb0NhVHNGeWZxU1JNUnU0ZmhBSFVOSHUxTUM2bwprajBXYm9GdmgraW11QUhRMTg5WgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
AVI_CONTROL_PLANE_NETWORK: user-workload
AVI_CONTROL_PLANE_NETWORK_CIDR: 10.220.26.64/27
AVI_CONTROLLER: avi01.h2o-4-18527.h2o.vmware.com
AVI_DATA_NETWORK: user-workload
AVI_DATA_NETWORK_CIDR: 10.220.26.64/27
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_CIDR: 10.220.26.64/27
AVI_MANAGEMENT_CLUSTER_CONTROL_PLANE_VIP_NETWORK_NAME: user-workload
AVI_MANAGEMENT_CLUSTER_SERVICE_ENGINE_GROUP: Default-Group
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 10.220.26.64/27
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: user-workload
AVI_PASSWORD: <encoded:TldKV0VyXjEyZUg4ZGh4UXdPdg==>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_ANNOTATIONS: 'description:,location:'
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: mgmt01
CLUSTER_PLAN: prod
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "true"
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: photon
OS_VERSION: "3"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: ""
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /vc01
VSPHERE_DATASTORE: /vc01/datastore/vsanDatastore
VSPHERE_FOLDER: /vc01/vm/TKG
VSPHERE_INSECURE: "true"
VSPHERE_NETWORK: /vc01/network/user-workload
VSPHERE_PASSWORD: <encoded:TldKV0VyXjEyZUg4ZGh4UXdPdg==>
VSPHERE_RESOURCE_POOL: /vc01/host/vc01cl01/Resources
VSPHERE_SERVER: vc01.h2o-4-18527.h2o.vmware.com
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXlD9JoI6owGuqKlU3dEalT4uMftXBNRdVbalpZGiKqvlKz8nrXsw9spi8i5s0KlF2WivAk5/dNCS3KNP5YoFl8MOsePiFgy7m8+kfx4Iwixdvq4g48l40k2C8kh8ydCi27eOQ/Ge81d6Rnun57fdAHwIS9hiROeB5tDxx+UJMGU0pjrjcCUU7nlm3zt6cN/jtK24jwH6s08VXzgFrQWnmDGQjfkt8tCLtO9ggzuIEhiFqQ/KeWn7/cqgeQeIIwws2ek84piqDA4U79bTGkTavGCpzZKILqHI7kujOr43coYZbLNqBtk1TYaFjoiC23eBRSYd/4MrIOjnDvrxxfEdJ viktor@dt01
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
WORKER_ROLLOUT_STRATEGY: ""
