# Enter the domain info
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nilab.io
  namespace: cert-manager
spec:
  secretName: tap-gui
  issuerRef:
    name: letsencrypt-prod
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  dnsNames:
    - "tap-gui.nilab.io"